### ISSUE TITLE
Getting none encryption error when select none in swiftmailer

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/core-framework#297]
![Screenshot (13)](https://user-images.githubusercontent.com/43210406/81277042-78c37100-9071-11ea-90d5-53422aa5aa3d.png)

**Comment by papnoisanjeev** [comment]
@vaishaliwebkul 

We have removed **None** option from [here](https://github.com/uvdesk/core-framework/commit/11302a2080191ed491b97b53b06ce59b2fcd70c5) and updated on master branch. Now this option will be removed in next release of project.


**For now you can do following step to remove this error:** 

As you have selected **"Encryption Mode - None"** for swift-mailer.  while setting it up for SMTP.
And swift mailer does not support **encryption: none** .
so you just need to locate and open file **swiftmailer.yaml** under
**config->packages** in your project.

Now change **encryption** to **tls or ssl** instead of **none** as per support by your email server and save your file. 
Now run your project and error will be removed.
