### ISSUE TITLE
> @papnoisanjeev, the table **uv_website** is created, columns with name, data empty.

### ISSUE THREAD

**Issue by dksdheeraj** [uvdesk/core-framework#312]
> @papnoisanjeev, the table **uv_website** is created, columns with name, data empty.
> **uv_website_knowledgebase** is not created, even without errors in log.

The same issue I am facing. Any solution?

_Originally posted by @dksdheeraj in https://github.com/uvdesk/core-framework/issues/278#issuecomment-670338055_

**Comment by papnoisanjeev** [comment]
@dksdheeraj 

This problem generally comes when your **max_execution_time** is less in **php.ini** and due to this migration or fixture does not load properly. so you need to increase it before setup project as also instructed in doc.


If you want to setup manually then try below method instructed in comment below.

https://github.com/uvdesk/community-skeleton/issues/290#issuecomment-661113642
