### ISSUE TITLE
all the apps are visible to agent in search even they don't have privilege to manage

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/core-framework#329]
**Description**  
all the apps are visible to an agent in search even they don't have the privilege to manage

**How to reproduce**  
1. create an agent without having any privilege
2. login with agent account
3. search the mailbox, groups, teams, workflow, email settings, etc..

**Additional context**  
All these apps should not visible
![Screenshot_67](https://user-images.githubusercontent.com/43210406/96335608-8e64aa00-1097-11eb-8250-87e95077fdd0.png)

**Comment by papnoisanjeev** [comment]
@vaishaliwebkul 

Fixed in master branches.
mailbox bundle: https://github.com/uvdesk/mailbox-component/commit/7b8b1a661b7d90c5c966e067f4701491e5cd0244
core-framework: https://github.com/uvdesk/core-framework/commit/b273734a42a4497e192d2c7c3019f6c222a19efe
support-center bundle: https://github.com/uvdesk/support-center-bundle/commit/625842a7c168472912a95a46e538e1525c40c282
automation-bundle : https://github.com/uvdesk/automation-bundle/commit/bf8a5b8bec5cf60e329beb87fc28fee87cb73f72

**Comment by vaishaliwebkul** [comment]
@papnoisanjeev 
agent have customer, article, category, folder privilege, still, he is not able to search for these keys
![Screenshot_248](https://user-images.githubusercontent.com/43210406/106911773-8739d880-6728-11eb-8814-6e8d6830ae0e.png)

**Comment by papnoisanjeev** [comment]
@vaishaliwebkul 

Fixed Search section [here](https://github.com/uvdesk/core-framework/commit/847e2cfbb0f02e39dda4b19aa7dca886dbf6187e).
Added missing component in search  bar.

**Comment by vaishaliwebkul** [comment]
fixed
